# Let start Pandas

In [1]:
pip install pandas

Requirement already satisfied: pandas in /Users/sanmeshjadhav/Desktop/Data Science/.venv/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /Users/sanmeshjadhav/Desktop/Data Science/.venv/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sanmeshjadhav/Desktop/Data Science/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sanmeshjadhav/Desktop/Data Science/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [ ]:
#create :series from list

marks=[80,90,70]
series1=pd.Series(marks)

In [4]:
series1

0    80
1    90
2    70
dtype: int64

In [7]:
#series with our index
s2=pd.Series([80,90,100],index=['Alice','Bob','sam'])

In [8]:
s2

Alice     80
Bob       90
sam      100
dtype: int64

In [9]:
import numpy as np

In [12]:
arr=np.array([10,20,30])

arr

array([10, 20, 30])

In [13]:
arr.dtype

dtype('int64')

In [14]:
arr.ndim

1

In [16]:
series3=pd.Series([10,20,30])
s3=pd.Series(arr)

In [17]:
s3

0    10
1    20
2    30
dtype: int64

In [18]:
series4=pd.Series([50,60,70,80,90],index=["sam","raj","aniket","deeya","ram"])

In [19]:
series4

sam       50
raj       60
aniket    70
deeya     80
ram       90
dtype: int64

In [20]:
dict={"mango":100,"banana":200,"grapes":300,"apple":400}
series5=pd.Series(dict)

In [21]:
series5

mango     100
banana    200
grapes    300
apple     400
dtype: int64

In [22]:
#let create more values with dict
students=[
    {"name":"sam","age":22},
    {"name":"raj","age":25},
    {"name":"aniket","age":30}
]

In [23]:
students

[{'name': 'sam', 'age': 22},
 {'name': 'raj', 'age': 25},
 {'name': 'aniket', 'age': 30}]

In [ ]:
#usinng dataframe to create a table like structure
students_df=pd.DataFrame(students)

In [27]:
students_df

     name  age
0     sam   22
1     raj   25
2  aniket   30

In [28]:
#other way to create dataframe from dict
data={
    "name":["ravi","raj","sam"],
    "age":[22,25,30],
    "city":["pune","mumbai","delhi"]
}

In [29]:
data_df=pd.DataFrame(data)

In [30]:
data_df

   name  age    city
0  ravi   22    pune
1   raj   25  mumbai
2   sam   30   delhi

In [34]:
#let save the data
data_df.to_csv("students.csv")

In [36]:
#load save this data
data_df=pd.read_csv("students.csv")

In [37]:
data_df

   Unnamed: 0  name  age    city
0           0  ravi   22    pune
1           1   raj   25  mumbai
2           2   sam   30   delhi

In [40]:
data_df.to_excel("students.xlsx")

In [39]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [42]:
data_df=pd.read_excel("students.xlsx")

In [43]:
data_df

   Unnamed: 0.1  Unnamed: 0  name  age    city
0             0           0  ravi   22    pune
1             1           1   raj   25  mumbai
2             2           2   sam   30   delhi

In [44]:
data_df.head(1)

   Unnamed: 0.1  Unnamed: 0  name  age  city
0             0           0  ravi   22  pune

In [45]:
data_df.head()

   Unnamed: 0.1  Unnamed: 0  name  age    city
0             0           0  ravi   22    pune
1             1           1   raj   25  mumbai
2             2           2   sam   30   delhi

In [46]:
data_df.head(2)

   Unnamed: 0.1  Unnamed: 0  name  age    city
0             0           0  ravi   22    pune
1             1           1   raj   25  mumbai