In [5]:
import pandas as pd

In [6]:
#create the dataframe
#example 1 student data frame
df=pd.DataFrame(
    {
        "Name": ["sanmesh", "ram", "aniket"],
        "Age": [25, 30, 35],
        "City": ["pune", "mumbai", "kolhapur"]
    },

    
    index=["A", "B", "C"]
)

In [14]:
df

      Name  Age      City
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur

In [15]:
df.head()

      Name  Age      City
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur

In [16]:
df.head(1)

      Name  Age  City
A  sanmesh   25  pune

In [ ]:
#pic all rows of the dataframe
df.head(3)

      Name  Age      City
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur

In [ ]:
#pic last 2 rows of the dataframe
df.tail(2)

     Name  Age      City
B     ram   30    mumbai
C  aniket   35  kolhapur

In [ ]:
# Get the shape of the dataframe(rows, columns)
df.shape

(3, 3)

In [ ]:
# Get information about the dataframe
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, A to C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 96.0+ bytes

In [ ]:
# Get descriptive statistics for the dataframe
df.describe()

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [ ]:
# Get column names of the dataframe
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [ ]:
# Get the index of the dataframe
df.index

Index(['A', 'B', 'C'], dtype='str')

In [ ]:
# Get the data types of the dataframe
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [8]:
#selecting Data
df=pd.DataFrame(
    {
        "Name": ["sanmesh", "ram", "aniket","raj"],
        "Age": [25, 30, 35,20],
        "City": ["pune", "mumbai", "kolhapur","satara"]
    },
    index=["A", "B", "C","D"]
)

In [40]:

df["Name"]

A    sanmesh
B        ram
C     aniket
D        raj
Name: Name, dtype: str

In [41]:
df[["Name", "Age"]]

      Name  Age
A  sanmesh   25
B      ram   30
C   aniket   35
D      raj   20

In [ ]:

df[["Name","Age"]].head(2)

      Name  Age
A  sanmesh   25
B      ram   30

In [ ]:
# Selecting the last 2 rows of specific columns
df[["Name", "Age"]].tail(2)

     Name  Age
2  aniket   35
3     raj   20

In [ ]:
# Selecting a specific row
df.loc["A"]

Name    sanmesh
Age          25
City       pune
Name: A, dtype: object

In [45]:
# Selecting multiple rows
df.loc["A":"D"]

      Name  Age      City
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur
D      raj   20    satara

In [48]:
df.loc["A","Name"]

'sanmesh'

In [50]:
df.iloc[2:4]

     Name  Age      City
C  aniket   35  kolhapur
D     raj   20    satara

In [52]:
df.iloc[1]

Name       ram
Age         30
City    mumbai
Name: B, dtype: object

In [ ]:
# Selecting rows based on a condition
df[df["Age"] > 22]

      Name  Age      City
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur

In [55]:
df[df["Age"] ==25]

      Name  Age  City
A  sanmesh   25  pune

In [57]:
df[df["Name"] == "raj"]

  Name  Age    City
D  raj   20  satara

In [62]:
df[df["City"] == "pune"]

      Name  Age  City
A  sanmesh   25  pune

In [66]:
df[df["City"].str.lower() == "mumbai"]

  Name  Age    City
B  ram   30  mumbai

In [67]:
df.sort_values("Age")

      Name  Age      City
D      raj   20    satara
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur

In [ ]:
df.sort_values("Name") #deafult A to Z

      Name  Age      City
C   aniket   35  kolhapur
D      raj   20    satara
B      ram   30    mumbai
A  sanmesh   25      pune

In [ ]:
df.sort_values("Name", ascending=False) #for Z to A

      Name  Age      City
A  sanmesh   25      pune
B      ram   30    mumbai
D      raj   20    satara
C   aniket   35  kolhapur

In [9]:
df.head()

      Name  Age      City
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur
D      raj   20    satara

In [ ]:
# Rename the 'City' column to 'Location'
new_df=df.rename(columns={"City":"Location"})

In [23]:
new_df

      Name  Age  Location
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur
D      raj   20    satara

In [ ]:
# Rename the 'Age' column to 'user age'
new_df=df.rename(columns={"Age":"user age"})

In [19]:
new_df

      Name  user age      City
A  sanmesh        25      pune
B      ram        30    mumbai
C   aniket        35  kolhapur
D      raj        20    satara

In [ ]:
# Rename the 'Name' column to 'First_Name'
new_df=df.rename(columns={"Name":"First_Name"})

In [21]:
new_df

  First_Name  Age      City
A    sanmesh   25      pune
B        ram   30    mumbai
C     aniket   35  kolhapur
D        raj   20    satara

In [ ]:
# Update the 'Name' value for row "A"
df.loc["A","Name"]="Rahul"

In [30]:
new_df

      Name  Age  Location
A  sanmesh   25      pune
B      ram   30    mumbai
C   aniket   35  kolhapur
D      raj   20    satara

In [31]:
df

     Name  Age      City
A   Rahul   25      pune
B     ram   30    mumbai
C  aniket   35  kolhapur
D     raj   20    satara

In [ ]:
# Update the 'City' value for row "D"
df.loc["D","City"]="Nagpur"

In [35]:
df

     Name  Age      City
A   Rahul   25      pune
B     ram   30    mumbai
C  aniket   35  kolhapur
D     raj   20    Nagpur

In [36]:
#Boolean mask:
df["Age"]>=23

A     True
B     True
C     True
D    False
Name: Age, dtype: bool

In [ ]:
#city=Nagpur
df["City"]=="Nagpur"

A    False
B    False
C    False
D     True
Name: City, dtype: bool

In [39]:
features=df[["Age","City"]]

In [40]:
features

   Age      City
A   25      pune
B   30    mumbai
C   35  kolhapur
D   20    Nagpur

In [41]:
features_df=df.copy()
features_df

     Name  Age      City
A   Rahul   25      pune
B     ram   30    mumbai
C  aniket   35  kolhapur
D     raj   20    Nagpur

In [44]:
features_df["Age_Group"]=features_df["Age"].apply(lambda Age: "Young" if Age<30 else "adult")

In [45]:
features_df

     Name  Age      City Age_Group
A   Rahul   25      pune     Young
B     ram   30    mumbai     adult
C  aniket   35  kolhapur     adult
D     raj   20    Nagpur     Young

In [47]:
features_df[features_df["Age"]>22]

     Name  Age      City Age_Group
A   Rahul   25      pune     Young
B     ram   30    mumbai     adult
C  aniket   35  kolhapur     adult

In [48]:
#missing values
df_missing=df.copy()

In [53]:
df_missing.head()

     Name  Age      City
A   Rahul   25      pune
B     ram   30    mumbai
C  aniket   35  kolhapur
D     raj   20    Nagpur

In [56]:
df_missing.loc["C","City"]=None

In [64]:
df_missing.loc["A","Age"]=None
df_missing

     Name   Age    City
A   Rahul   NaN    pune
B     ram  30.0  mumbai
C  aniket  35.0     NaN
D     raj  20.0  Nagpur
c     NaN   NaN     NaN

In [58]:
df_missing

     Name   Age    City
A   Rahul  25.0    pune
B     ram  30.0  mumbai
C  aniket  35.0     NaN
D     raj  20.0  Nagpur
c     NaN   NaN     NaN

In [66]:
df_missing.isnull()

    Name    Age   City
A  False   True  False
B  False  False  False
C  False  False   True
D  False  False  False
c   True   True   True

In [65]:
df_missing.isnull().sum()

Name    1
Age     2
City    2
dtype: int64

In [67]:
#Drop null values
df_missing.dropna()

  Name   Age    City
B  ram  30.0  mumbai
D  raj  20.0  Nagpur

In [68]:
df_missing

     Name   Age    City
A   Rahul   NaN    pune
B     ram  30.0  mumbai
C  aniket  35.0     NaN
D     raj  20.0  Nagpur
c     NaN   NaN     NaN

In [71]:
df_missing.dropna(subset=["City"])

    Name   Age    City
A  Rahul   NaN    pune
B    ram  30.0  mumbai
D    raj  20.0  Nagpur

In [72]:
df_missing.dropna(subset=["Age"])

     Name   Age    City
B     ram  30.0  mumbai
C  aniket  35.0     NaN
D     raj  20.0  Nagpur

In [73]:
df_missing.dropna(subset=["Name"])

     Name   Age    City
A   Rahul   NaN    pune
B     ram  30.0  mumbai
C  aniket  35.0     NaN
D     raj  20.0  Nagpur

In [76]:
#Fill NA
fill=df_missing.fillna({"City":"Unknown"})

In [77]:
fill

     Name   Age     City
A   Rahul   NaN     pune
B     ram  30.0   mumbai
C  aniket  35.0  Unknown
D     raj  20.0   Nagpur
c     NaN   NaN  Unknown

In [79]:
age_mean=fill["Age"].mean()

In [80]:
age_mean

np.float64(28.333333333333332)

In [89]:
fill["Age"]=fill["Age"].fillna(age_mean)

In [90]:
fill

     Name        Age     City
A   Rahul  28.333333     pune
B     ram  30.000000   mumbai
C  aniket  35.000000  Unknown
D     raj  20.000000   Nagpur
c     NaN  28.333333  Unknown