## Array
# 1D Array
# 2D Array
# 3D Array

In [1]:
#1D array
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]

# Attributes

In [3]:
#Attributes
print(np.ndim(a))
print(np.shape(a))
print(np.size(a))
print(a.dtype)

1
(7,)
7
int64

In [5]:
#2D array
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [6]:
print(np.ndim(b))
print(np.shape(b))
print(np.size(b))
print(b.dtype)

2
(3, 3)
9
int64

In [7]:
#3D array
c=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])

print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

In [8]:
print(np.ndim(c))
print(np.shape(c))
print(np.size(c))
print(c.dtype)

3
(1, 3, 3)
9
int64

In [12]:
d=np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [3,4,2],
        [5,3,1],
        [6,4,8]
    ]
])

print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 4 2]
  [5 3 1]
  [6 4 8]]]

In [13]:
print(np.ndim(d))
print(np.shape(d))
print(np.size(d))
print(d.dtype)

3
(2, 3, 3)
18
int64

In [17]:
#practice questions

#1
a=np.array([10,20,30,40,50])
print(a)

print(np.ndim(a))
print(np.shape(a))
print(np.size(a))

[10 20 30 40 50]
1
(5,)
5

In [18]:
#2
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

print(np.ndim(a))
print(np.shape(a))
print(np.size(a))

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
10

In [21]:
#3
b=np.array([[1,2,9],
            [4,7,6]])

print(b)

print(np.ndim(b))
print(np.shape(b))
print(np.size(b))

[[1 2 9]
 [4 7 6]]
2
(2, 3)
6

In [22]:
#4

#3
b=np.array([[1,2,3],
            [4,5,6]])

print(b)

print(np.ndim(b))
print(np.shape(b))
print(np.size(b))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6

In [25]:
#5
a=np.array([
    [
        [1,2,3],
        [3,4,5]
    ],
    [
        [1,3,5],
        [2,4,6]
    ]
])

print(a)
print(np.ndim(a))
print(np.shape(a))
print(np.size(a))

[[[1 2 3]
  [3 4 5]]

 [[1 3 5]
  [2 4 6]]]
3
(2, 2, 3)
12

In [26]:
#6
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [28]:
print(a)
print(np.ndim(a))
print(np.shape(a))
print(np.size(a))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
3
(1, 4, 3)
12

In [29]:
#7
a=np.array([1,2,3])
print(a)

[1 2 3]

In [31]:
#8
a=np.array([[1,2],[3,4],[5,6]])
print(a)

print(np.shape(a))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

In [36]:
#9
#3D array
c=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])

print(c)

print(np.shape(a))
print(np.ndim(a))
print(np.size(a))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 2)
2
6

In [37]:
#10
#1D array
a=np.array([1,2,3,4,5,6,7])
print(a)
print(np.shape(a))
print(np.ndim(a))
print(np.size(a))

#2D array
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(b)
print(np.shape(b))
print(np.ndim(b))
print(np.size(b))

#3D array
c=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])

print(c)
print(np.shape(c))
print(np.ndim(c))
print(np.size(c))

[1 2 3 4 5 6 7]
(7,)
1
7
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
3
9

# Array functions

In [40]:
#Array functions
#ones
one=np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [43]:
#zeros
zero=np.zeros((5,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [44]:
#full
full=np.full((4,5),10)
print(full)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]

In [45]:
#random.rand
a=np.random.rand(4,4)
print(a)

[[0.24078974 0.16375664 0.08577725 0.55072925]
 [0.3721711  0.75892246 0.5356351  0.59055432]
 [0.04779806 0.89896964 0.85487942 0.0695388 ]
 [0.58942552 0.21422927 0.25170136 0.79466516]]

In [46]:
#random.randn
a=np.random.randn(3,4)
print(a)

[[-0.07246024 -0.63610598  0.58337904 -0.97732662]
 [-0.34912793 -1.21420122 -0.48672716 -0.669713  ]
 [ 1.13410733  0.84810014 -1.89462795 -0.36774871]]

In [53]:
#random.randint
a=np.random.randint(1,10,(5,5))
print(a)

[[8 9 1 2 2]
 [5 4 4 1 2]
 [5 6 5 6 8]
 [2 7 6 9 5]
 [9 7 7 4 7]]

In [63]:
#arrange
a=np.arange(1,11,2)
print(a)

[1 3 5 7 9]

In [62]:
#eye
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

# Indexing and slicing

In [1]:
#Indexing and slicing
import numpy as np

In [ ]:
#1D
a=np.array([10,20,30,40,50,60])
a

array([10, 20, 30, 40, 50, 60])

In [3]:
print(a[2])

30

In [ ]:
#2D
b=np.random.randint(1,10,(3,3))

In [5]:
b

array([[2, 9, 6],
       [8, 6, 4],
       [7, 1, 6]])

In [7]:
print(b[0,0])

2

In [8]:
print(b[2,1])

1

In [9]:
print(b[1,2])

4

In [ ]:
#3D
b=np.random.randint(1,10,(2,3,3))
b

array([[[4, 9, 1],
        [7, 4, 2],
        [6, 9, 9]],

       [[8, 7, 8],
        [4, 7, 3],
        [2, 6, 1]]])

In [15]:
print(b[0,1,2])

2

In [16]:
print(b[1,2,0])

2

In [17]:
print(b[0,2,2])

9

In [18]:
print(b[0,2,0])

6

In [19]:
print(b[1,0,0])

8

In [ ]:
#slicing
#1D
b=np.array([10,20,30,40,50])
b

array([10, 20, 30, 40, 50])

In [25]:
print(b[1:4])

[20 30 40]

In [26]:
print(b[2:5])

[30 40 50]

In [ ]:
#2D
a=np.random.randint(1,10,(3,3))
a

array([[5, 4, 4],
       [5, 6, 6],
       [8, 4, 1]])

In [28]:
print(a[0:2,1:3])

[[4 4]
 [6 6]]

In [29]:
print(a[1:3,0:2])

[[5 6]
 [8 4]]

In [30]:
print(a[0:2,0:2])

[[5 4]
 [5 6]]

In [31]:
print(a[0:1,:])

[[5 4 4]]

In [36]:
print(a[:,1:2])

[[4]
 [6]
 [4]]

In [42]:
print(a[1:2,:])

[[5 6 6]]

In [43]:
print(a[2:3,:])

[[8 4 1]]

In [44]:
print(a[:,2:3])

[[4]
 [6]
 [1]]

In [45]:
print(a[:,1:2])

[[4]
 [6]
 [4]]

In [ ]:
#3D
a=np.random.randint(1,10,(2,3,3))
a

array([[[9, 2, 4],
        [8, 7, 1],
        [6, 9, 5]],

       [[3, 8, 5],
        [7, 4, 3],
        [5, 4, 2]]])

In [48]:
print(a[1,0:1,:])

[[3 8 5]]

In [49]:
print(a[0,0:2,0:2])

[[9 2]
 [8 7]]

In [50]:
print(a[1,0:2,1:3])

[[8 5]
 [4 3]]

In [56]:
print(a[0,1:2,:])

[[8 7 1]]

In [57]:
print(a[1,:,1:2])

[[8]
 [4]
 [4]]

In [58]:
print(a[1,1,1])

4

In [60]:
print(a[1:2,2:3,2:3])

[[[2]]]

## ~Other topics
# 1->Array manipulation 
# a.reshape()
# b.flatten()
# c.ravel()
# d.concatenate()
# e.transpose()

## 2->Mathematical functions
# a.sum()
# b.min()
# c.max()
# d.abs()
# e.STD()
# f.var()

## 3->Fancy indexing
## 4->Boolean indexing
## 5->Brodcasting

In [1]:
import numpy as np

In [ ]:
#Array manipulation 
#Reshape
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

s = a.reshape(2,5)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

In [13]:
#Flatten
a=np.random.randint(1,10,(3,3))
a
print(a.flatten())

[5 7 2 2 9 1 2 8 5]

In [ ]:
#ravel
print(a.ravel())

[5 7 2 2 9 1 2 8 5]

In [26]:
#Transpose
a=np.random.randint(1,15,(4,4))
print(a)
print('')
print(a.transpose())

[[ 9  6 14  2]
 [ 3  8 10  9]
 [ 2  8  8  8]
 [10  8  1  4]]

[[ 9  3  2 10]
 [ 6  8  8  8]
 [14 10  8  1]
 [ 2  9  8  4]]

In [24]:
#Concatenate
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]

In [31]:
#Mathematical Function
a=np.random.randint(1,15,(4,4))
a

array([[ 4,  7, 13,  9],
       [13, 10,  7,  5],
       [ 1,  1,  5,  4],
       [ 8, 12,  4, 10]])

In [32]:
#min
print(np.min(a))

1

In [33]:
#max
print(np.max(a))

13

In [34]:
#sum
print(np.sum(a))

113

In [36]:
#abs
b=np.array([-1,-2,-3])
print(np.abs(b))

[1 2 3]

In [37]:
#STD
print(np.std(a))

3.7661112237957073

In [38]:
#var
print(np.var(a))

14.18359375

In [44]:
#Boolean indexing
a=np.random.randint(1,10,(4,4))
print(a)
print('')
print(a[a>5])

[[9 7 3 2]
 [6 6 6 8]
 [3 1 3 6]
 [6 4 9 3]]

[9 7 6 6 6 8 6 6 9]

In [41]:
print(a[a%2==0])

[8 2 6 4 8 6 2 2 6]

In [46]:
print(a==6)

[[False False False False]
 [ True  True  True False]
 [False False False  True]
 [ True False False False]]

In [50]:
#Fancy indexing
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [52]:
print(a[[0,3,4]])

[1 4 5]

In [ ]:
a=np.random.randint(1,10,(3,3))
a

array([[2, 5, 8],
       [4, 2, 9],
       [7, 3, 8]])

In [55]:
print(a[[0,2],[1,2]])

[5 8]

In [56]:
print(a[[0,2],[2,0]])

[8 7]

In [57]:
print(a[[1,2],[2,1]])

[9 3]

In [58]:
#Brodcasting
a=np.array([10,20,30,40,50])
b=np.array([20,10,40,60,70])

print(a+b)

[ 30  30  70 100 120]

In [ ]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
b=np.array([20,12,34])

In [64]:
print(a+b)

[[21 14 37]
 [24 17 40]
 [27 20 43]]

In [2]:
#read the Csv file
import pandas as pd
df=pd.read_csv('/Users/sanmeshjadhav/Library/Containers/net.whatsapp.WhatsApp/Data/tmp/documents/BE900EF5-7BFC-4A2B-9885-576BCFD423B9/Raw Mobile Sales Dataset.csv')

In [3]:
df

,Transaction ID,Day,month,Year,Brand,Units Sold,Price Per Unit,Customer Name,Customer Age,City,Payment Method,Customer Ratings,Mobile Model
0,1,9,10,2021,Xiaomi,6.0,10174.70,Lalita Ahuja,38.0,Ludhiana,UPI,5.0,Redmi Note 10
1,2,9,10,2021,Vivo,6.0,10565.19,Sneha Sharma,37.0,Delhi,Credit Card,3.0,Vivo Y51
2,3,9,10,2021,Vivo,8.0,58527.58,Radha Srivastava,40.0,Mumbai,UPI,5.0,Vivo S1
3,4,10,10,2021,Xiaomi,5.0,25563.98,Bhavana Arora,21.0,Mumbai,Credit Card,4.0,Mi 11
4,5,10,10,2021,OnePlus,3.0,48168.02,Sneha Mehta,38.0,Gorakhpur,Cash,5.0,OnePlus 9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3839,3831,7,10,2024,OnePlus,9.0,43406.12,Kavita Bhatnagar,41.0,Mumbai,Cash,5.0,OnePlus 8T
3840,3832,8,10,2024,Xiaomi,8.0,34675.31,Vivek Sheth,25.0,Jodhpur,UPI,2.0,Redmi 9
3841,3833,8,10,2024,OnePlus,7.0,37620.23,Anita Desai,34.0,Vadodara,UPI,5.0,OnePlus 8T
3842,3834,8,10,2024,OnePlus,4.0,16961.04,Ayesha Rathod,51.0,Mumbai,Debit Card,5.0,OnePlus 8T
3843,3835,8,10,2024,Samsung,1.0,50375.07,Sanjay Malhotra,37.0,Patna,UPI,3.0,Galaxy A51

In [13]:
#Data understanding
#head
df.head()

,Transaction ID,Day,month,Year,Brand,Units Sold,Price Per Unit,Customer Name,Customer Age,City,Payment Method,Customer Ratings,Mobile Model
0,1,9,10,2021,Xiaomi,6.0,10174.70,Lalita Ahuja,38.0,Ludhiana,UPI,5.0,Redmi Note 10
1,2,9,10,2021,Vivo,6.0,10565.19,Sneha Sharma,37.0,Delhi,Credit Card,3.0,Vivo Y51
2,3,9,10,2021,Vivo,8.0,58527.58,Radha Srivastava,40.0,Mumbai,UPI,5.0,Vivo S1
3,4,10,10,2021,Xiaomi,5.0,25563.98,Bhavana Arora,21.0,Mumbai,Credit Card,4.0,Mi 11
4,5,10,10,2021,OnePlus,3.0,48168.02,Sneha Mehta,38.0,Gorakhpur,Cash,5.0,OnePlus 9

In [8]:
#tail
df.tail()

,Transaction ID,Day,month,Year,Brand,Units Sold,Price Per Unit,Customer Name,Customer Age,City,Payment Method,Customer Ratings,Mobile Model
3839,3831,7,10,2024,OnePlus,9.0,43406.12,Kavita Bhatnagar,41.0,Mumbai,Cash,5.0,OnePlus 8T
3840,3832,8,10,2024,Xiaomi,8.0,34675.31,Vivek Sheth,25.0,Jodhpur,UPI,2.0,Redmi 9
3841,3833,8,10,2024,OnePlus,7.0,37620.23,Anita Desai,34.0,Vadodara,UPI,5.0,OnePlus 8T
3842,3834,8,10,2024,OnePlus,4.0,16961.04,Ayesha Rathod,51.0,Mumbai,Debit Card,5.0,OnePlus 8T
3843,3835,8,10,2024,Samsung,1.0,50375.07,Sanjay Malhotra,37.0,Patna,UPI,3.0,Galaxy A51

In [15]:
#shape
df.shape

(3844, 13)

In [ ]:
#dtypes
df.dtypes

Transaction ID        int64
Day                   int64
month                 int64
Year                  int64
Brand                   str
Units Sold          float64
Price Per Unit      float64
Customer Name           str
Customer Age        float64
City                    str
Payment Method          str
Customer Ratings    float64
Mobile Model            str
dtype: object

In [20]:
#isnull
df.isnull()

,Transaction ID,Day,month,Year,Brand,Units Sold,Price Per Unit,Customer Name,Customer Age,City,Payment Method,Customer Ratings,Mobile Model
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3839,False,False,False,False,False,False,False,False,False,False,False,False,False
3840,False,False,False,False,False,False,False,False,False,False,False,False,False
3841,False,False,False,False,False,False,False,False,False,False,False,False,False
3842,False,False,False,False,False,False,False,False,False,False,False,False,False
3843,False,False,False,False,False,False,False,False,False,False,False,False,False

In [22]:
#fillna
df.fillna

<bound method NDFrame.fillna of       Transaction ID  Day  month  Year    Brand  Units Sold  Price Per Unit  \
0                  1    9     10  2021   Xiaomi         6.0        10174.70
1                  2    9     10  2021     Vivo         6.0        10565.19
2                  3    9     10  2021     Vivo         8.0        58527.58
3                  4   10     10  2021   Xiaomi         5.0        25563.98
4                  5   10     10  2021  OnePlus         3.0        48168.02
...              ...  ...    ...   ...      ...         ...             ...
3839            3831    7     10  2024  OnePlus         9.0        43406.12
3840            3832    8     10  2024   Xiaomi         8.0        34675.31
3841            3833    8     10  2024  OnePlus         7.0        37620.23
3842            3834    8     10  2024  OnePlus         4.0        16961.04
3843            3835    8     10  2024  Samsung         1.0        50375.07

         Customer Name  Customer Age       City Payment Method  \
0         Lalita Ahuja          38.0   Ludhiana            UPI
1         Sneha Sharma          37.0      Delhi    Credit Card
2     Radha Srivastava          40.0     Mumbai            UPI
3        Bhavana Arora          21.0     Mumbai    Credit Card
4          Sneha Mehta          38.0  Gorakhpur           Cash
...                ...           ...        ...            ...
3839  Kavita Bhatnagar          41.0     Mumbai           Cash
3840       Vivek Sheth          25.0    Jodhpur            UPI
3841       Anita Desai          34.0   Vadodara            UPI
3842     Ayesha Rathod          51.0     Mumbai     Debit Card
3843   Sanjay Malhotra          37.0      Patna            UPI

      Customer Ratings   Mobile Model
0                  5.0  Redmi Note 10
1                  3.0       Vivo Y51
2                  5.0        Vivo S1
3                  4.0          Mi 11
4                  5.0      OnePlus 9
...                ...            ...
3839               5.0     OnePlus 8T
3840               2.0        Redmi 9
3841               5.0     OnePlus 8T
3842               5.0     OnePlus 8T
3843               3.0     Galaxy A51

[3844 rows x 13 columns]>

In [ ]:
#unique
df['Brand'].unique()

<StringArray>
['Xiaomi', 'Vivo', 'OnePlus', 'Samsung', 'Apple', nan]
Length: 6, dtype: str

In [24]:
#value_count
df['Brand'].value_counts()

Brand
Apple      779
Samsung    770
OnePlus    767
Vivo       764
Xiaomi     742
Name: count, dtype: int64

In [25]:
#info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3844 entries, 0 to 3843
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3844 non-null   int64
 1   Day               3844 non-null   int64
 2   month             3844 non-null   int64
 3   Year              3844 non-null   int64
 4   Brand             3822 non-null   str
 5   Units Sold        3823 non-null   float64
 6   Price Per Unit    3844 non-null   float64
 7   Customer Name     3844 non-null   str
 8   Customer Age      3821 non-null   float64
 9   City              3816 non-null   str
 10  Payment Method    3844 non-null   str
 11  Customer Ratings  3813 non-null   float64
 12  Mobile Model      3844 non-null   str
dtypes: float64(4), int64(4), str(5)
memory usage: 390.5 KB

In [26]:
#describe
df.describe()

,Transaction ID,Day,month,Year,Units Sold,Price Per Unit,Customer Age,Customer Ratings
count,3844.000000,3844.000000,3844.000000,3844.000000,3823.000000,3844.000000,3821.000000,3813.000000
mean,1922.478928,15.684183,6.535380,2022.768210,4.994507,40104.144493,38.100759,3.688434
std,1109.775214,8.821776,3.452069,0.918267,2.581932,17302.757307,12.118527,1.326328
min,1.000000,1.000000,1.000000,2021.000000,1.000000,10011.110000,18.000000,1.000000
25%,961.750000,8.000000,4.000000,2022.000000,3.000000,25624.227500,27.000000,3.000000
50%,1922.500000,16.000000,7.000000,2023.000000,5.000000,40133.105000,38.000000,4.000000
75%,2883.250000,23.000000,10.000000,2024.000000,7.000000,54958.380000,49.000000,5.000000
max,3835.000000,31.000000,12.000000,2024.000000,9.000000,69984.480000,59.000000,5.000000

In [28]:
#columns
df.columns

Index(['Transaction ID', 'Day', 'month', 'Year', 'Brand', 'Units Sold',
       'Price Per Unit', 'Customer Name', 'Customer Age', 'City',
       'Payment Method', 'Customer Ratings', 'Mobile Model'],
      dtype='str')